language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - xavi.sanchez.mir@gmail.com
script:
#Test unitario y de integracion en develop
- mvn clean verify --settings settings.xml
- mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify --settings settings.xml
- mvn sonar:sonar -Dsonar.organization=xavism-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR --settings settings.xml
