language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - xavi.sanchez.mir@gmail.com
script:
#Test unitario y de integracion en develop
- mvn verify --settings settings.xml
